---
# dopy is required for ansible digital_ocean module
- name: Install dopy (required for DigitalOcean API).
  easy_install: name=dopy

- name: Display image_id used for droplet creation.
  debug:
    msg: >
      Creating droplet from image_id {{ droplet_image_id }}

- name: Create DigitalOcean droplet.
  digital_ocean:
    command: droplet
    state: present
    name: "{{ droplet_name | mandatory }}"
    unique_name: "{{ droplet_unique_name }}"

    size_id: "{{ droplet_size_id }}"
    region_id: "{{ droplet_region_id }}"
    image_id: "{{ droplet_image_id }}"
    private_networking: "{{ droplet_private_networking }}"

    api_token: "{{ digitalocean_api_token }}"
    # Oddly, the Ansible docs say that `ssh_key_ids` should be
    # a comma-separated list, but passing in a YAML list works.
    #ssh_key_ids: "{{ digitalocean_ssh_key_ids | join(',') }}"
    ssh_key_ids: "{{ digitalocean_ssh_key_ids }}"
    wait: "{{ droplet_wait }}"
    wait_timeout: "{{ droplet_wait_timeout }}"
  register: new_droplet
  tags:
    - digital_ocean
    - provision

