---
- name: Query DigitalOcean API for SSH key ids.
  script: do-listkeys
  register: do_listkeys_result
  changed_when: false

- name: Set fetched SSH key id as host fact.
  set_fact:
    digitalocean_ssh_key_ids:
      - "{{ do_listkeys_result.stdout | trim }}"
