---
- name: Install 'barge' gem for querying DigitalOcean API.
  gem:
    name: barge
    state: present

- name: Query DigitalOcean API for SSH key ids.
  script: do-listkeys
  register: do_listkeys_result
  changed_when: false

- name: Set fetched SSH key id as host fact.
  set_fact:
    digitalocean_ssh_key_ids:
      # The 'trim' filter is necessary here because the `script`
      # module preserves newlines on STDOUT, whereas `command` does not.
      - "{{ do_listkeys_result.stdout | trim }}"
