---
# dopy is required for ansible digital_ocean module
- name: ensure dopy is installed (for digitalocean API)
  easy_install: name=dopy

- name: create digitalocean droplet
  digital_ocean:
    command: droplet
    state: present
    name: "{{ droplet_name | mandatory }}"
    unique_name: "{{ unique_name }}"

    size_id: "{{ size_id }}"
    region_id: "{{ region_id }}"
    image_id: "{{ image_id }}"

    api_token: "{{ do_api_token }}"
    ssh_key_ids: "{{ ssh_key_ids | join(',') }}"
    wait: "{{ wait }}"
    wait_timeout: "{{ wait_timeout }}"
  register: new_droplet
  tags:
    - digital_ocean
    - provision

- name: flush old IPs from SSH known_hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ new_droplet.droplet.ip_address }}'
  when: new_droplet.changed

- name: add new IP to SSH known_hosts
  shell: 'ssh-keyscan -H -T 10 {{ new_droplet.droplet.ip_address }} >> "$HOME/.ssh/known_hosts"'
  when: new_droplet.changed

- name: add droplet to inventory
  add_host:
    name: "{{ droplet_name }}"
    groups: "{{ droplet_groups }}"
  when: droplet_groups is defined and droplet_groups != ''

- name: warn about adding droplet to inventory
  debug:
    msg: >
     Created new host '{{ droplet_name }}'. Rerun this playbook
     so it's included in the inventory.
  when: new_droplet.changed





- name: set domain name
  do_domain:
    domain: "{{ domain_name }}"
    ip_address: new_droplet.droplet.ip_address
  when: domain_name is defined and
        domain_name != ''
