---
# dopy is required for ansible digital_ocean module
- name: ensure dopy is installed (for digitalocean API)
  easy_install: name=dopy

- name: create digitalocean droplet
  digital_ocean:
    command: droplet
    state:
    name: "{{ droplet_name | mandatory }}"
    unique_name: "{{ unique_name }}"

    size_id: "{{ size_id }}"
    region_id: "{{ region_id }}"
    image_id: "{{ image_id }}"

    api_token: "{{ do_api_token }}"
    ssh_key_ids: "{{ do_ssh_key_id }}"
    wait_timeout: 200
  register: new_droplet
  tags:
    - digital_ocean
    - provision

- name: flush old IPs from SSH known_hosts
  shell: 'ssh-keygen -f "$HOME/.ssh/known_hosts" -R {{ new_droplet.droplet.ip_address }}'
  when: new_droplet.changed

- name: add new IP to SSH known_hosts
  shell: 'ssh-keyscan -H -T 10 {{ new_droplet.droplet.ip_address }} >> "$HOME/.ssh/known_hosts"'
  when: new_droplet.changed
